MartUretimTakipMVC/Models/Database/GecmisHareket.cs
using PagedList;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MartUretimTakipMVC.Models.Database
{
    public class GecmisHareket
    {
        [Key]
        public int HareketID { get; set; }
        public string EklenmeTarihi { get; set; }

        public string DuzenlenmeTarihi { get; set; }

        [Column(TypeName = "Nvarchar")]
        [StringLength(20)]
        [Display(Name = "Stok Kodu")]
        public string StokKodu { get; set; }

        [Column(TypeName = "Varchar")]
        [StringLength(20)]
        [Display(Name = "DID")]
        public string DID { get; set; }

        [Column(TypeName = "Nvarchar")]
        [StringLength(3)]
        public string Parti { get; set; }

        [Column(TypeName = "Nvarchar")]
        [StringLength(6)]
        public string Lot { get; set; }

        [Column(TypeName = "Nvarchar")]
        [Display(Name = "Önceki Adet")]
        public string OncekiAdet { get; set; }

        [Column(TypeName = "Nvarchar")]
        [Display(Name = "Sonraki Adet")]
        public string SonrakiAdet { get; set; }

        [Column(TypeName = "Nvarchar")]
        [StringLength(1)]
        [Display(Name = "Depo")]
        public string Depo { get; set; }

        [Column(TypeName = "Varchar")]
        [StringLength(1)]
        [Display(Name = "Düzenlenecek")]
        public string Duzenlenecek { get; set; }

        [Column(TypeName = "Varchar")]
        [StringLength(5)]
        [Display(Name = "Düzenlendi")]
        public string Duzenlendi { get; set; }

        [Column(TypeName = "Nvarchar")]
        [StringLength(1)]
        [Display(Name = "Durum")]
        public string Durum { get; set; }

        [Column(TypeName = "Varchar")]
        [StringLength(100)]
        [Display(Name = "Kullanıcı")]
        public string Kullanici { get; set; }

        [Column(TypeName = "Nvarchar")]
        [StringLength(100)]
        [Display(Name = "Düzenleyen Kullanıcı")]
        public string DuzenleyenKullanici { get; set; }

        [Column(TypeName = "Nvarchar")]
        [StringLength(100)]
        [Display(Name = "Not")]
        public string Not { get; set; }

        public ICollection<Yonetici> Yoneticis { get; set; }
    }
}

MartUretimTakipMVC/Controllers/GecmisHareketController.cs
using ClosedXML.Excel;
using MartUretimTakipMVC.Models.Database;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web.Mvc;
using System.Web.UI.WebControls;
using PagedList;

namespace MartUretimTakipMVC.Controllers
{
    public class GecmisHareketController : Controller
    {
        // GET: GecmisHareket
        Context db = new Context();

        [Authorize(Roles = "3,2")]
        public ActionResult Index(int sayfa = 1)
        {
            var topveri = db.GecmisHarekets.Count();
            ViewBag.ToplamHareket = topveri;
            var username = Session["YoneticiIsim"] as string;
            ViewBag.Kullanici = username;
            var gecmishareket = db.GecmisHarekets.OrderByDescending(x => x.HareketID).ToPagedList(sayfa, 100);
            return View(gecmishareket);
        }

        [Authorize(Roles = "3,2")]
        public ActionResult SayimGeriAl(GecmisHareket gh, DepoSayim ds, EtiketsizSayim es)
        {
            var sayim = db.GecmisHarekets.Find(gh.HareketID);
            if (sayim.Durum == "P")
            {
                if (ds.StokKodu.Length == 8 && ds.Parti.Length == 2 && ds.Lot.Length == 5 && ds.DID.Length == 15 && ds.Depo.Length == 1)
                {
                    string stokkodu = ds.DID.Substring(0, 8);
                    string parti = ds.DID.Substring(8, 2);
                    string lot = ds.DID.Substring(10, 5);
                    if (ds.StokKodu == stokkodu && ds.Parti == parti && ds.Lot == lot)
                    {
                        db.DepoSayimlar.Add(ds);
                        ds.EklenmeTarih = sayim.EklenmeTarihi;
                        ds.DuzenlenmeTarih = sayim.DuzenlenmeTarihi;
                        ds.StokKodu = sayim.StokKodu;
                        ds.DID = sayim.DID;
                        ds.Parti = gh.Parti;
                        ds.Lot = gh.Lot;
                        ds.OncekiAdet = sayim.OncekiAdet;
                        ds.Adet = gh.SonrakiAdet;
                        ds.Duzenlenecek = sayim.Duzenlenecek;
                        ds.Duzenlendi = sayim.Duzenlendi;
                        ds.Depo = sayim.Depo;
                        ds.Durum = "A";
                        ds.Kullanici = sayim.Kullanici;
                        ds.DuzenleyenKullanici = sayim.DuzenleyenKullanici;
                        db.GecmisHarekets.Remove(sayim);
                        db.SaveChanges();
                        return RedirectToAction("Index", "DepoSayim");
                    }
                    else
                    {
                        ViewBag.Msg = "DID Bilgisi Hatalı";
                        return View("SayimGetir", sayim);
                    }
                }
                else
                {
                    ViewBag.Msg = "Girilen Bilgiler Hatalı";
                    return View("SayimGetir", sayim);
                }
            }
            else
            {
                ViewBag.Msg = "Bu Malzeme Silinmemiş";
                return View("SayimGetir", sayim);
            }
        }

        [Authorize(Roles = "3,2")]
        public ActionResult SayimGetir(int id)
        {
            var sayim = db.GecmisHarekets.Find(id);
            if (sayim.DID != null)
            {
                return View("SayimGetir", sayim);
            }
            else
            {
                return View("EtiketsizSayimGetir", sayim);
            }
        }

        public ActionResult EtiketsizSayimGetir(int id)
        {
            var etiketsizsayim = db.GecmisHarekets.Find(id);
            return View("EtiketsizSayimGetir", etiketsizsayim);
        }

        public ActionResult EtiketsizSayimGeriAl(EtiketsizSayim es, GecmisHareket gh)
        {
            var sayim = db.GecmisHarekets.Find(gh.HareketID);
            if (sayim.Durum == "P")
            {
                db.EtiketsizSayims.Add(es);
                es.EklenmeTarih = sayim.EklenmeTarihi;
                es.DuzenlenmeTarih = sayim.DuzenlenmeTarihi;
                es.StokKodu = sayim.StokKodu;
                es.OncekiAdet = sayim.OncekiAdet;
                es.Adet = sayim.SonrakiAdet;
                es.Kullanici = sayim.Kullanici;
                es.DuzenleyenKullanici = sayim.DuzenleyenKullanici;
                es.Durum = "A";
                es.Duzenlendi = sayim.Duzenlendi;
                es.Duzenlenecek = sayim.Duzenlenecek;
                es.Not = sayim.Not;
                db.GecmisHarekets.Remove(sayim);
                db.SaveChanges();
                return RedirectToAction("Index", "EtiketsizSayim");
            }
            else
            {
                ViewBag.Msg = "Bu malzeme silinmemiş";
                return View("EtiketsizSayimGetir", sayim);
            }
        }

        [Authorize(Roles = "3,2")]
        public ActionResult SilinenSayimlar(int sayfa = 1)
        {
            var silinenveri = db.GecmisHarekets.Where(x => x.Durum == "P").Count();
            ViewBag.ToplamHareket = silinenveri;
            var username = Session["YoneticiIsim"] as string;
            ViewBag.Kullanici = username;
            var silinensayim = db.GecmisHarekets.Where(x => x.Durum == "P").ToList();
            return View("Index", silinensayim.OrderByDescending(x => x.HareketID).ToPagedList(sayfa, 100));
        }

        [Authorize(Roles = "3,2")]
        public ActionResult DuzenlenenSayimlar(int sayfa = 1)
        {
            var duzenlenen = db.GecmisHarekets.Where(x => x.Duzenlendi == "Evet").Count();
            ViewBag.ToplamHareket = duzenlenen;
            var username = Session["YoneticiIsim"] as string;
            ViewBag.Kullanici = username;
            var duzenlenenler = db.GecmisHarekets.Where(x => x.Duzenlendi == "Evet").ToList();
            return View("Index", duzenlenenler.OrderByDescending(x => x.HareketID).ToPagedList(sayfa, 100));
        }

        public ActionResult ExcelAktarma()
        {
            var topveri = db.GecmisHarekets.Count();
            ViewBag.ToplamHareket = topveri;
            string tarih = System.DateTime.Now.ToString("dd.MM.yyyy_HH.mm");

            using (var workbook = new XLWorkbook())
            {
                var gecmishareketlist = db.GecmisHarekets.ToList();
                var ws = workbook.Worksheets.Add("Geçmiş Hareketler");
                ws.Cell(1, 1).Value = "Eklenme Tarihi";
                ws.Cell(1, 2).Value = "Düzenlenme Tarihi";
                ws.Cell(1, 3).Value = "Stok Kodu";
                ws.Cell(1, 4).Value = "DID";
                ws.Cell(1, 5).Value = "Parti";
                ws.Cell(1, 6).Value = "Lot";
                ws.Cell(1, 7).Value = "Önceki Adet";
                ws.Cell(1, 8).Value = "Sonraki Adet";
                ws.Cell(1, 9).Value = "Depo";
                ws.Cell(1, 10).Value = "Durum";
                ws.Cell(1, 11).Value = "Düzenlenecek";
                ws.Cell(1, 12).Value = "Düzenlendi";
                ws.Cell(1, 13).Value = "Kullanıcı";
                ws.Cell(1, 14).Value = "Düzenleyen";
                ws.Cell(1, 15).Value = "Not";

                int row = 2;

                foreach (var item in gecmishareketlist)
                {
                    ws.Cell(row, 1).Value = item.EklenmeTarihi;
                    ws.Cell(row, 2).Value = item.DuzenlenmeTarihi;
                    ws.Cell(row, 3).Value = item.StokKodu;
                    ws.Cell(row, 4).Value = item.DID;
                    ws.Cell(row, 5).Value = item.Parti;
                    ws.Cell(row, 6).Value = item.Lot;
                    ws.Cell(row, 7).Value = item.OncekiAdet;
                    ws.Cell(row, 8).Value = item.SonrakiAdet;
                    ws.Cell(row, 9).Value = item.Depo;
                    ws.Cell(row, 10).Value = item.Durum;
                    ws.Cell(row, 11).Value = item.Duzenlenecek;
                    ws.Cell(row, 12).Value = item.Duzenlendi;
                    ws.Cell(row, 13).Value = item.Kullanici;
                    ws.Cell(row, 14).Value = item.DuzenleyenKullanici;
                    ws.Cell(row, 15).Value = item.Not;
                    row++;
                }

                var titles = ws.Cells("A1:N1").Style.Font.Bold = true;

                ws.Column(1).Width = 17; // 1. sütun
                ws.Column(2).Width = 17; // 2. sütun
                ws.Column(3).Width = 10; // 3. sütun
                ws.Column(4).Width = 17; // 4. sütun
                ws.Column(7).Width = 12; // 7. sütun
                ws.Column(8).Width = 12; // 8. sütun
                ws.Column(11).Width = 13; // 11. sütun
                ws.Column(12).Width = 13; // 12. sütun
                ws.Column(13).Width = 17; // 13. sütun
                ws.Column(14).Width = 17; // 13. sütun
                ws.Column(15).Width = 25; // 14. sütun


                using (var stream = new MemoryStream())
                {
                    workbook.SaveAs(stream);
                    var content = stream.ToArray();
                    return File(content, "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "GecmisHareket (" + tarih + ").xlsx");
                }
            }
        }

        public ActionResult TersSiralama(int sayfa = 1)
        {
            var topveri = db.GecmisHarekets.Count();
            ViewBag.ToplamHareket = topveri;
            var gecmishareket = db.GecmisHarekets.OrderBy(x => x.HareketID).ToList();
            return View("Index", gecmishareket.OrderBy(x => x.HareketID).ToPagedList(sayfa, 100));
        }

        public ActionResult Filter(string filter, int sayfa = 1)
        {
            var topveri = db.GecmisHarekets.Count();
            ViewBag.ToplamHareket = topveri;
            var sayims = from s in db.GecmisHarekets
                         select s;
            if (!string.IsNullOrEmpty(filter))
            {
                sayims = sayims.Where(x => x.StokKodu.Equals(filter) || x.DID.Equals(filter));
            }

MartUretimTakipMVC/Views/GecmisHareket/EtiketsizSayimGetir.cshtml
@model MartUretimTakipMVC.Models.Database.GecmisHareket
@{
    ViewBag.Title = "EtiketsizSayimGetir";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<br />
<h2>Etiketsiz Sayım Geri Al</h2>
<br />
<h3 style="color:red;">@ViewBag.Msg</h3>
@using (Html.BeginForm("EtiketsizSayimGeriAl", "GecmisHareket", FormMethod.Post))
{
    <div class="form-group">
        @Html.HiddenFor(x => x.HareketID)
        @Html.LabelFor(x => x.EklenmeTarihi)
        @Html.TextBoxFor(x => x.EklenmeTarihi, new { style = "width:300px; text-align:center; font-size:19px;  ", required = "required", disabled = "disabled", @class = "form-control" })
        <br />
        @Html.LabelFor(x => x.DuzenlenmeTarihi)
        @Html.TextBoxFor(x => x.DuzenlenmeTarihi, new { style = "width:300px; text-align:center; font-size:19px;  ", required = "required", disabled = "disabled", @class = "form-control" })
        <br />
        @Html.LabelFor(x => x.StokKodu)
        @Html.TextBoxFor(x => x.StokKodu, new { style = "width:300px; text-align:center; font-size:19px;  ", onkeypress = "javascript:return isChar(event)", autocomplete = "off", required = "required", @class = "form-control" })
        <br />
        @Html.LabelFor(x => x.OncekiAdet)
        @Html.TextBoxFor(x => x.OncekiAdet, new { style = "width:300px; text-align:center; font-size:19px;  ", autocomplete = "off", disabled = "disabled", @class = "form-control" })
        <br />
        @Html.LabelFor(x => x.SonrakiAdet)
        @Html.TextBoxFor(x => x.SonrakiAdet, new { style = "width:300px; text-align:center; font-size:19px;  ", onkeypress = "javascript:return isChar(event)", autocomplete = "off", @class = "form-control" })
        <br />
        @Html.LabelFor(x => x.Duzenlenecek)
        @Html.TextBoxFor(x => x.Duzenlenecek, new { style = "width:300px; text-align:center; font-size:19px;  ", required = "required", disabled = "disabled", autocomplete = "off", @class = "form-control" })
        <br />
        @Html.LabelFor(x => x.Duzenlendi)
        @Html.TextBoxFor(x => x.Duzenlendi, new { style = "width:300px; text-align:center; font-size:19px;  ", required = "required", autocomplete = "off", disabled = "disabled", @class = "form-control" })
        <br />       
        @Html.LabelFor(x => x.Kullanici)
        @Html.TextBoxFor(x => x.Kullanici, new { style = "width:300px; text-align:center; font-size:19px;  ", disabled = "disabled", @class = "form-control" })
        <br />
        <button class="btn btn-primary">Kaydet</button>
    </div>
}

MartUretimTakipMVC/Views/GecmisHareket/Index.cshtml
@using MartUretimTakipMVC.Models.Database
@using PagedList
@using PagedList.Mvc
@model PagedList.IPagedList<MartUretimTakipMVC.Models.Database.GecmisHareket>
@{
    ViewBag.Title = "Geçmiş Hareketler";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<script src="https://kit.fontawesome.com/b4ef86249b.js" crossorigin="anonymous"></script>
<script>
    function oturumuKapat() {
        $.ajax({
            url: '/Giris/CikisYap', // Oturumu kapatma işlemini gerçekleştirecek MVC controller'ın URL'sini belirtin
            type: 'POST',
            dataType: 'json',
        });
    }

    // Sekme kapatıldığında oturumu kapatma işlemi
    window.onunload = function () {
        oturumuKapat();
    }
</script>
<br />
<h3>Geçmiş Depo Sayım Hareketleri - Toplam Hareket : @ViewBag.ToplamHareket</h3>
<br />
<a href="/GecmisHareket/TersSiralama" class="btn btn-warning" title="Ters Sıralama" style="background-color:orange; color:white; margin-left:5px;"><i class="fa-solid fa-arrow-down-z-a"></i></a>
<a href="/GecmisHareket/EtiketsizSayim" class="btn btn-primary" title="Etiketsiz Sayımları Listele"><i class="fa-solid fa-qrcode"></i></a>
<a href="/GecmisHareket/SilinenSayimlar" style="margin-left:5px;" title="Silinen Sayımları Listele" class="btn btn-danger"><i class="fa fa-trash"></i></a>
<a href="/GecmisHareket/DuzenlenenSayimlar" style="margin-left:5px;" title="Düzenlenen Sayımları Listele" class="btn btn-warning"><i style="color:white;" class="fa fa-pen"></i></a>
<a href="/GecmisHareket/ExcelAktarma" class="btn btn-primary" title="Excel Olarak Kaydet" style="margin-left:1000px;  background-color:green; color:white;  margin-left:5px;"><i class="fa-solid fa-file-excel"></i></a>
<div style="float:right; margin-right:1000px;">
    @using (Html.BeginForm("Filter", "GecmisHareket", FormMethod.Get))
    {
        @Html.TextBox("filter")
        <button type="submit">Ara</button>
    }
</div>
<br />
<br />
<table class="table table-hover" style="width:1200px;">
    <tr>
        <th>HareketID</th>
        <th>Eklenme Tarihi</th>
        <th>Düzenlenme Tarihi</th>
        <th>Stok Kodu</th>
        <th style="padding-left:55px;">DID</th>
        <th>Parti</th>
        <th>Lot</th>
        <th>Önceki Adet</th>
        <th>Sonraki Adet</th>
        <th>Düzenlenecek</th>
        <th>Düzenlendi</th>
        <th>Depo</th>
        <th>Durum</th>
        <th>Kullanıcı</th>
        <th>Düzenleyen</th>
        <th>Not</th>
        <th>İşlemler</th>
    </tr>
    @foreach (var gh in Model)
    {
        <tr>
            <td style="padding-left:28px;">@gh.HareketID</td>
            <td style="padding-left:10px;">@gh.EklenmeTarihi</td>
            <td style="padding-left:20px;">@gh.DuzenlenmeTarihi</td>
            <td>@gh.StokKodu</td>
            <td>@gh.DID</td>
            <td>@gh.Parti</td>
            <td>@gh.Lot</td>
            <td style="padding-left:35px;">@gh.OncekiAdet</td>
            <td style="padding-left:20px;">@gh.SonrakiAdet</td>
            <td style="padding-left:50px;">@gh.Duzenlenecek</td>
            <td style="padding-left:35px;">@gh.Duzenlendi</td>
            <td style="padding-left:25px;">@gh.Depo</td>
            <td style="padding-left:25px;">@gh.Durum</td>
            <td>@gh.Kullanici</td>
            <td style="padding-left:25px;">@gh.DuzenleyenKullanici</td>
            <td>@gh.Not</td>
            <td><a id="SayimGeriAl" style="margin-left:15px;" class="btn btn-primary" title="Depo Sayımlarına Al" href="/GecmisHareket/SayimGetir/@gh.HareketID"><i class="fa-solid fa-arrows-rotate"></i></a></td>
        </tr>
    }
</table>
@Html.PagedListPager((IPagedList)Model, sayfa => Url.Action("Index", new { sayfa }), new PagedListRenderOptions
{
    LiElementClasses = new List<string>
    {"page-link"}
})

MartUretimTakipMVC/Views/GecmisHareket/SayimGetir.cshtml
@model MartUretimTakipMVC.Models.Database.GecmisHareket
@{
    ViewBag.Title = " Sayım Geri Al";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<script>
    function oturumuKapat() {
        $.ajax({
            url: '/Giris/CikisYap', // Oturumu kapatma işlemini gerçekleştirecek MVC controller'ın URL'sini belirtin
            type: 'POST',
            dataType: 'json',
        });
    }

    // Sekme kapatıldığında oturumu kapatma işlemi
    window.onunload = function () {
        oturumuKapat();
    }

    function isChar(evt) {
        var iKeyCode = (evt.which) ? evt.which : evt.keyCode
        if ((iKeyCode < 48 || iKeyCode > 57))
            return false;

        return true;
    }
</script>
<h3>Sayım Geri Al</h3>
<br />
<h3 style="color:red;">@ViewBag.Msg</h3>
@using (Html.BeginForm("SayimGeriAl", "GecmisHareket", FormMethod.Post))
{
    <div class="form-group">
        @Html.HiddenFor(x => x.HareketID)
        @Html.LabelFor(x => x.EklenmeTarihi)
        @Html.TextBoxFor(x => x.EklenmeTarihi, new { style = "width:300px; text-align:center; font-size:19px;  ", required = "required", disabled = "disabled", @class = "form-control" })
        <br />
        @Html.LabelFor(x => x.DuzenlenmeTarihi)
        @Html.TextBoxFor(x => x.DuzenlenmeTarihi, new { style = "width:300px; text-align:center; font-size:19px;  ", required = "required", disabled = "disabled", @class = "form-control" })
        <br />
        @Html.LabelFor(x => x.StokKodu)
        @Html.TextBoxFor(x => x.StokKodu, new { style = "width:300px; text-align:center; font-size:19px;  ", onkeypress = "javascript:return isChar(event)", autocomplete = "off", required = "required", @class = "form-control" })
        <br />
        @Html.LabelFor(x => x.DID)
        @Html.TextBoxFor(x => x.DID, new { style = "width:300px; text-align:center; font-size:19px;  ", onkeypress = "javascript:return isChar(event)", autocomplete = "off", required = "required", @class = "form-control" })
        <br />
        @Html.LabelFor(x => x.Parti)
        @Html.TextBoxFor(x => x.Parti, new { style = "width:300px; text-align:center; font-size:19px;  ", onkeypress = "javascript:return isChar(event)", autocomplete = "off", required = "required", @class = "form-control" })
        <br />
        @Html.LabelFor(x => x.Lot)
        @Html.TextBoxFor(x => x.Lot, new { style = "width:300px; text-align:center; font-size:19px;  ", onkeypress = "javascript:return isChar(event)", autocomplete = "off", required = "required", @class = "form-control" })
        <br />
        @Html.LabelFor(x => x.OncekiAdet)
        @Html.TextBoxFor(x => x.OncekiAdet, new { style = "width:300px; text-align:center; font-size:19px;  ", autocomplete = "off", disabled="disabled", @class = "form-control" })
        <br />
        @Html.LabelFor(x => x.SonrakiAdet)
        @Html.TextBoxFor(x => x.SonrakiAdet, new { style = "width:300px; text-align:center; font-size:19px;  ", onkeypress = "javascript:return isChar(event)", autocomplete = "off", @class = "form-control" })
        <br />
        @Html.LabelFor(x => x.Duzenlenecek)
        @Html.TextBoxFor(x => x.Duzenlenecek, new { style = "width:300px; text-align:center; font-size:19px;  ", required = "required", disabled="disabled", autocomplete = "off", @class = "form-control" })
        <br />
        @Html.LabelFor(x => x.Duzenlendi)
        @Html.TextBoxFor(x => x.Duzenlendi, new { style = "width:300px; text-align:center; font-size:19px;  ", required = "required", autocomplete = "off", disabled="disabled", @class = "form-control" })
        <br />
        @Html.LabelFor(x => x.Depo)
        @Html.TextBoxFor(x => x.Depo, new { style = "width:300px; text-align:center; font-size:19px;  ", onkeypress = "javascript:return isChar(event)", autocomplete = "off", required = "required", @class = "form-control" })
        <br />
        @Html.LabelFor(x => x.Kullanici)
        @Html.TextBoxFor(x => x.Kullanici, new { style = "width:300px; text-align:center; font-size:19px;  ", disabled = "disabled", @class = "form-control" })
        <br />
        <button class="btn btn-primary">Kaydet</button>
    </div>
}