MartUretimTakipMVC/Controllers/KullaniciController.cs
using DocumentFormat.OpenXml.EMMA;
using MartUretimTakipMVC.Models.Database;
using System.Linq;
using System.Web.Mvc;
using System.Web.UI.WebControls;

namespace MartUretimTakipMVC.Controllers
{
    public class KullaniciController : Controller
    {
        // GET: Kullanici
        Context db = new Context();

        [Authorize(Roles = "3,2")]
        public ActionResult Index()
        {
            var topkullanici = db.Yoneticiler.Count();
            ViewBag.ToplamKullanici = topkullanici;
            var kullanici = db.Yoneticiler.Where(x => x.YoneticiDurum == "A").ToList();
            return View(kullanici);
        }

        [Authorize(Roles = "3,2")]
        [HttpGet]
        public ActionResult KullaniciEkle()
        {
            return View();
        }

        [Authorize(Roles = "3,2")]
        [HttpPost]
        public ActionResult KullaniciEkle(Yonetici y)
        {
            db.Yoneticiler.Add(y);
            y.YoneticiDurum = "A";
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [Authorize(Roles = "3,2")]
        public ActionResult KullaniciGetir(int id)
        {
            var kullanici = db.Yoneticiler.Find(id);
            return View("KullaniciGetir", kullanici);
        }

        public ActionResult KullaniciDuzenle(Yonetici y)
        {            
            var kullanici = db.Yoneticiler.Find(y.KayıtID);
            kullanici.YoneticiID = y.YoneticiID;
            kullanici.YoneticiSifre = y.YoneticiSifre;
            kullanici.YoneticiYetki = y.YoneticiYetki;
            kullanici.YoneticiGorev = y.YoneticiGorev;
            kullanici.YoneticiIsim = y.YoneticiIsim;
            db.SaveChanges();           
            return RedirectToAction("Index");
        }

        [Authorize(Roles = "3")]
        public ActionResult KullaniciSil(int id)
        {
            var kullanici = db.Yoneticiler.Find(id);
            kullanici.YoneticiDurum = "P";
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

MartUretimTakipMVC/Views/Kullanici/Index.cshtml
@using MartUretimTakipMVC.Models.Database
@model List<Yonetici>
@{
    ViewBag.Title = "Kullanıcılar";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<script src="https://kit.fontawesome.com/b4ef86249b.js" crossorigin="anonymous"></script>
<script>
    function oturumuKapat() {
        $.ajax({
            url: '/Giris/CikisYap', // Oturumu kapatma işlemini gerçekleştirecek MVC controller'ın URL'sini belirtin
            type: 'POST',
            dataType: 'json',
        });
    }

    // Sekme kapatıldığında oturumu kapatma işlemi
    window.onunload = function () {
        oturumuKapat();
    }
</script>
<br />
<h3>Kullanıcılar | <span>Toplam Kullanıcı: @ViewBag.ToplamKullanici</span></h3>
<br />
<a href="/Kullanici/KullaniciEkle" class="btn btn-primary" title="Kullanıcı Ekle" style="margin-left:10px;"><i class="fa fa-user-plus"></i></a>
<br />
<br />
<table class="table table-hover" style="width:800px;">
    <tr>
        <th style="padding-left:17px;">Yönetici</th>
        <th style="padding-left:40px;">ID</th>
        <th style="padding-left:30px;">Şifre</th>
        <th style="padding-left:30px;">Görev</th>
        <th>Yetki</th>
        <th colspan="2" style="padding-left:40px;">İşlemler</th>
    </tr>
    @foreach (var k in Model)
    {
        <tr>
            <td>@k.YoneticiIsim</td>
            <td>@k.YoneticiID</td>
            <td>@k.YoneticiSifre</td>
            <td>@k.YoneticiGorev</td>
            <td style="padding-left:22px;">@k.YoneticiYetki</td>
            <td><a href="/Kullanici/KullaniciGetir/@k.KayıtID" class="btn btn-warning" title="Kullanıcı Düzenle" style="background-color:orange; color:white;"><i class="fa-solid fa-user-pen"></i></a></td>
            <td>@Html.ActionLink("Sil", "KullaniciSil", new { id = k.KayıtID }, new { style = "color:white;", @class = "btn btn-danger", onclick = "return confirm('Kullanıcıyı silmek istediğinize emin misiniz?')" })</td>
        </tr>
    }
</table>

MartUretimTakipMVC/Views/Kullanici/KullaniciEkle.cshtml
@model MartUretimTakipMVC.Models.Database.Yonetici
@{
    ViewBag.Title = "Kullanıcı Ekle";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<script>
    function oturumuKapat() {
        $.ajax({
            url: '/Giris/CikisYap', // Oturumu kapatma işlemini gerçekleştirecek MVC controller'ın URL'sini belirtin
            type: 'POST',
            dataType: 'json',
        });
    }

    // Sekme kapatıldığında oturumu kapatma işlemi
    window.onunload = function () {
        oturumuKapat();
    }

    window.onload = function () {
        document.getElementById("YoneticiID").focus();
    }
</script>
<br />
<h2>Kullanıcı Ekle</h2>
<br />
<form class="form-group" method="post">
    @Html.LabelFor(x => x.YoneticiID)<span style="color:red; padding-left:5px;">*</span>
    @Html.TextBoxFor(x => x.YoneticiID, new { id = "YoneticiID", style = "width:380px; text-align:center; font-size:19px; ", required = "required", autocomplete = "off", @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.YoneticiIsim)<span style="color:red; padding-left:5px;">*</span>
    @Html.TextBoxFor(x => x.YoneticiIsim, new { style = "width:380px; text-align:center; font-size:19px; ", required = "required", autocomplete = "off", @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.YoneticiSifre)<span style="color:red; padding-left:5px;">*</span>
    @Html.TextBoxFor(x => x.YoneticiSifre, new { style = "width:380px; text-align:center; font-size:19px; ", required = "required", autocomplete = "off", @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.YoneticiGorev)<span style="color:red; padding-left:5px;">*</span>
    @Html.TextBoxFor(x => x.YoneticiGorev, new { style = "width:380px; text-align:center; font-size:19px; ", required = "required", autocomplete = "off", @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.YoneticiYetki)<span style="color:red; padding-left:5px;">*</span>
    @Html.TextBoxFor(x => x.YoneticiYetki, new { style = "width:380px; text-align:center; font-size:19px; ", required = "required", autocomplete = "off", @class = "form-control" })
    <br />
    <button class="btn btn-primary">Ekle</button>
</form>

MartUretimTakipMVC/Views/Kullanici/KullaniciGetir.cshtml
@model MartUretimTakipMVC.Models.Database.Yonetici
@{
    ViewBag.Title = "Kullanıcı Düzenle";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<script>
    function oturumuKapat() {
        $.ajax({
            url: '/Giris/CikisYap', // Oturumu kapatma işlemini gerçekleştirecek MVC controller'ın URL'sini belirtin
            type: 'POST',
            dataType: 'json',
        });
    }

    // Sekme kapatıldığında oturumu kapatma işlemi
    window.onunload = function () {
        oturumuKapat();
    }
</script>
<br />
<h2>Kullanıcı Düzenleme</h2>
<br />
@using (Html.BeginForm("KullaniciDuzenle", "Kullanici", FormMethod.Post))
{
    <div class="form-group">
        @Html.HiddenFor(x => x.KayıtID)
        @Html.LabelFor(x => x.YoneticiIsim)
        @Html.TextBoxFor(x => x.YoneticiIsim, new { style = "width:380px; text-align:center; font-size:19px; ", required = "required", autocomplete = "off", @class = "form-control" })
        <br />
        @Html.LabelFor(x => x.YoneticiID)
        @Html.TextBoxFor(x => x.YoneticiID, new { style = "width:380px; text-align:center; font-size:19px; ", required = "required", autocomplete = "off", @class = "form-control" })
        <br />
        @Html.LabelFor(x => x.YoneticiSifre)
        @Html.TextBoxFor(x => x.YoneticiSifre, new { style = "width:380px; text-align:center; font-size:19px; ", required = "required", autocomplete = "off", @class = "form-control" })
        <br />
        @Html.LabelFor(x => x.YoneticiGorev)
        @Html.TextBoxFor(x => x.YoneticiGorev, new { style = "width:380px; text-align:center; font-size:19px; ", required = "required", autocomplete = "off", @class = "form-control" })
        <br />
        @Html.LabelFor(x => x.YoneticiYetki)
        @Html.TextBoxFor(x => x.YoneticiYetki, new { style = "width:380px; text-align:center; font-size:19px; ", required = "required", autocomplete = "off", @class = "form-control" })
        <br />
        @Html.LabelFor(x => x.YoneticiDurum)
        @Html.TextBoxFor(x => x.YoneticiDurum, new { style = "width:380px; text-align:center; font-size:19px; ", required = "required", autocomplete = "off", @class = "form-control" })
        <br />
        <button class="btn btn-primary">Değişiklikleri Kaydet</button>
    </div>
}